/**
 * Skill Utilities
 * Helper functions for skill operations
 */

const fs = require('fs').promises;
const path = require('path');

/**
 * Find all skills in a repository directory
 */
async function findAllSkillsInRepo(repoDir) {
  const skills = [];

  async function scan(dir) {
    try {
      const entries = await fs.readdir(dir, { withFileTypes: true });

      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
          const skillMdPath = path.join(fullPath, 'SKILL.md');
          try {
            await fs.access(skillMdPath);
            const content = await fs.readFile(skillMdPath, 'utf-8');
            const descMatch = content.match(/description: (.+)/);

            skills.push({
              name: entry.name,
              description: descMatch ? descMatch[1].trim() : '无描述',
              path: fullPath,
            });
          } catch {
            // Not a skill directory, continue recursion
            await scan(fullPath);
          }
        }
      }
    } catch {
      // Directory not readable, skip
    }
  }

  await scan(repoDir);
  return skills;
}

/**
 * Parse skill description from SKILL.md
 */
async function getSkillDescription(skillPath) {
  try {
    const skillMdPath = path.join(skillPath, 'SKILL.md');
    const content = await fs.readFile(skillMdPath, 'utf-8');
    const descMatch = content.match(/description: (.+)/);
    return descMatch ? descMatch[1].trim() : '无描述';
  } catch {
    return '无描述';
  }
}

/**
 * Generate AGENTS.md content
 */
function generateAgentsMd(skills) {
  const skillTags = skills
    .map(s => `  <skill>
    <name>${s.name}</name>
    <description>${s.description}</description>
    <location>${s.location}</location>
  </skill>`)
    .join('\n\n');

  return `# AI Agents Configuration

<!-- Auto-generated by Universal Skill Hub -->

<skills_system priority="1">

## Available Skills

<!-- SKILLS_TABLE_START -->
<usage>
When users ask you to perform tasks, check if any of the available skills below can help complete the task more effectively.

How to use skills:
- Invoke: Bash("openskills read <skill-name>")
- The skill content will load with detailed instructions
- Base directory provided for resolving bundled resources

Usage notes:
- Only use skills listed in <available_skills> below
- Do not invoke a skill that is already loaded in your context
</usage>

<available_skills>

${skillTags}

</available_skills>
<!-- SKILLS_TABLE_END -->

</skills_system>
`;
}

/**
 * Update skill registry with installation info
 */
async function updateSkillRegistry(registryPath, skill) {
  const content = await fs.readFile(registryPath, 'utf-8');
  const registry = JSON.parse(content);

  registry.skills[skill.name] = {
    description: skill.description,
    installedAt: new Date().toISOString(),
  };

  await fs.writeFile(registryPath, JSON.stringify(registry, null, 2));
}

/**
 * Parse GitHub source into repo URL and subpath
 */
function parseGitHubSource(source) {
  // Already a full URL
  if (source.startsWith('http://') || source.startsWith('https://')) {
    const url = new URL(source);
    const pathParts = url.pathname.split('/').filter(Boolean);

    // Handle https://github.com/owner/repo/tree/branch/subpath
    const treeIndex = pathParts.indexOf('tree');
    let repoOwner, repoName, subpath;

    if (treeIndex >= 2) {
      repoOwner = pathParts[treeIndex - 2];
      repoName = pathParts[treeIndex - 1];
      subpath = pathParts.slice(treeIndex + 2).join('/');
    } else {
      repoOwner = pathParts[0];
      repoName = pathParts[1];
      subpath = pathParts.slice(2).join('/');
    }

    return {
      repoUrl: `https://github.com/${repoOwner}/${repoName}`,
      subpath: subpath || '',
    };
  }

  // owner/repo or owner/repo/subpath format
  const parts = source.split('/');

  if (parts.length < 2) {
    throw new Error('无效的 source 格式');
  }

  return {
    repoUrl: `https://github.com/${parts[0]}/${parts[1]}`,
    subpath: parts.slice(2).join('/'),
  };
}

module.exports = {
  findAllSkillsInRepo,
  getSkillDescription,
  generateAgentsMd,
  updateSkillRegistry,
  parseGitHubSource,
};
